#pragma once
#include <d3d12.h>

struct INPUT_LAYOUT {
	//座標
	D3D12_INPUT_ELEMENT_DESC POSITION = {
		"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0,
		D3D12_APPEND_ALIGNED_ELEMENT,
		D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0
	};

	//2Duv座標
	D3D12_INPUT_ELEMENT_DESC UV_2D = {
		"TEXCOORD_2D", 0, DXGI_FORMAT_R32G32_FLOAT, 0,
		D3D12_APPEND_ALIGNED_ELEMENT,
		D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0
	};

	//3Duv座標
	D3D12_INPUT_ELEMENT_DESC UV_3D = {
		"TEXCOORD_3D", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0,
		D3D12_APPEND_ALIGNED_ELEMENT,
		D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0
	};

	//法線
	D3D12_INPUT_ELEMENT_DESC NORMAL = {
		"NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0,
		D3D12_APPEND_ALIGNED_ELEMENT,
		D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0
	};

	//ボーン番号
	D3D12_INPUT_ELEMENT_DESC BONEINDICES = {
		"BONEINDICES", 0, DXGI_FORMAT_R32G32B32A32_UINT, 0,
		D3D12_APPEND_ALIGNED_ELEMENT,
		D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0
	};

	//ボーン影響度
	D3D12_INPUT_ELEMENT_DESC BONEWEIGHTS = {
		"BONEWEIGHTS", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0,
		D3D12_APPEND_ALIGNED_ELEMENT,
		D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0
	};
};

enum INPUT_LAYOUT_NUMBER
{
	POSITION,
	TEXCOORD,
	TEXCOORD_2D,
	TEXCOORD_3D,
	NORMAL,
	BONEINDICES,
	BONEWEIGHTS,
};

enum BLEND_MODE
{
	NOBLEND,//デフォルト設定
	ALPHA,//α合成
	ADD,//加算合成
	SUB,//減算合成
	MULA,//乗算合成
	INVSRC,//反転合成
};